#pragma once


enum class SCENE_TYPE { INTRO , MAINMENU ,GAME, TYPEEND };

enum class OBJ_STATE {ALIVE, DEAD, TYPEEND};

enum class OBJ_TYPE { BACKPARTICLE, CLOUD ,MAP, STRUCTURE ,WORM, PROJECTILE, FLAMEPARTICLE ,TYPEEND};

enum class CLOUD_TYPE {NORMAL, SMALL, BLACK , TYPEEND};

enum class WORM_STATE{IDLE,WALK, WEAPON, JUMP, FlYING , SLIDE, DEAD, WINNER,SWIM,NOTTURN,TYPEEND};

enum class OBJ_DIR{LEFT,RIGHT,TYPEEND};

enum class ANIMATOR_STATE {SPRITE,BMP,TYPEEND};

enum class SPRITE_STATE {START,REVERSE,END,TYPEEND};

enum class WIND_DIR {LEFT, MIDDLE ,RIGHT, TYPEEND};

enum class WEAPON_TYPE {BAZOOKA,BANANA,DONKEY,HMISSILE,AIRMISSILE,BASEBALL,HOLY,STRUCTURE,SHEEP,METEOR,TELEPORT,TYPEEND};

enum class WEAPON_STATE {IDLE, GAGE, SHOOT, SHOOTEND ,TYPEEND};

enum class PROJECTILE_STATE {NONE, BOMB, END, TYPEEND};

enum class CIRCLE_EFFECT_TYPE { CIRCLE25, CIRCLE50, CIRCLE75, CIRCLE100, TYPEEND };

enum class ELLIPSE_EFFECT_TYPE {ELLIPSE25, ELLIPSE50, ELLIPSE75, ELLIPSE100, TYPEEND};

enum class EXHAUST_EFFECT_TYPE {WHITE,DARK,TYPEEND};

enum class SMOKE_EFFECT_TYPE {DARK20,DARK30,DARK40,WHITE25,WHITE50,WHITE75,WHITE100,TYPEEND};

enum class TEXT_EFFECT_TYPE {BIFF,POW,POOT,FOOM,TYPEEND};

enum class CAMERA_STATE {NORMAL,FOLLOWTARGET,GOTARGET,GETMOUSE,CAMERASHAKE,TYPEEND};

enum class WORM_JUMP_STATE {START, READY , FLYUP, FLY, FLYDOWN, LAND, END ,TYPEEND};

enum class WORM_SLIDE_STATE {SLIDE, END, TYPEEND};

enum class GAMEMGR_STATE {TURNSTART, TURNEND ,ENDSTART ,END, NEXTTURN, GAMEEND ,TYPEEND };

enum class INVEN_UI_STATE {DRAW,STOP,PUT,TYPEEND};

enum class BUBBLE_TYPE {BUBBLE1, BUBBLE2,BUBBLE3,BUBBLE4, TYPEEND};

enum class HMISSILE_TYPE {H1,H2, TYPEEND};

enum CHANNELID { SOUND_EFFECT, GAMESOUND,GAMESOUND2, BOMBSOUND1,BOMBSOUND2,BOMBSOUND3,BOMBSOUND4,BOMBSOUND5 ,PROJECTILE, WORMSPEECH, WORMSOUND ,WORMSOUND1,WORMSOUND2,WORMSOUND3,WORMSOUND4,WEAPONSOUND ,SOUND_BGM, MAXCHANNEL };
